### ISSUE TITLE
Could not load file or assembly Microsoft.Graph.Authentication.Core error

### ISSUE THREAD

**Issue by david-salac** [alan-turing-institute/data-safe-haven#1321] opened 2022-10-15 09:41 UTC
## :white_check_mark: Checklist

- [ ] I have searched open and closed issues for duplicates.
- [ ] This is a problem observed when **deploying** a Data Safe Haven.
- [ ] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [ ] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [ ] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** 
- **Data Safe Haven version:** 

## :no_entry_sign: Describe the problem

When I run the `Setup_SHM_AAD_Domain.ps1` command, I can see the following error - do you know what to do with that?

Also, do you have any `.devcontainer` that would make that deployment faster (so I wouldn't have to install all system-level dependencies)? It would really make life much easier.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```powershell
PS C:\*\setup> ./Setup_SHM_AAD_Domain.ps1 -shmId mcshdev

2022-10-15 10:27:16 [   INFO]: Ensuring that 'project.tre4mc.com' is registered with AAD...
Get-MgDomain_List1: C:\Users\admin\Projects\AlanTuring\TRE01\data-safe-haven\deployment\safe_haven_management_environment\setup\Setup_SHM_AAD_Domain.ps1:36:1
Line |
  36 |  $aadDomain = Get-MgDomain | Where-Object { $_.Id -eq $config.domain.f …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | One or more errors occurred. (Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.13.0.0,
     | Culture=neutral, PublicKeyToken=*******'. The system cannot find the file specified.)
```
</details>

**Comment by jemrobinson** [comment] 2022-10-17 08:21
It looks like this error is caused by a missing Powershell dependency (in this case `Microsoft.Graph.Authentication.Core`. You can run `/deployment)/CheckRequirements.ps1` to see the state of all your dependencies. Could you do this now and add the output to the appropriate section in your top-level post?

You can install missing dependencies by running `/deployment)/CheckRequirements.ps1 -InstallMissing`.

We don't have any kind of `.devcontainer` at the moment. If you think this would be useful, would you consider adding one in a PR?

**Comment by david-salac** [comment] 2022-10-17 21:19
Sure, here is the output of `./deployment/CheckRequirements.ps1 -InstallMissing`:
```
2022-10-17 22:08:47 [SUCCESS]: [✔] Powershell version: 7.2.6
2022-10-17 22:08:47 [SUCCESS]: [✔] Az.PrivateDns module version: 1.0.3
2022-10-17 22:08:47 [SUCCESS]: [✔] Poshstache module version: 0.1.10
2022-10-17 22:08:47 [SUCCESS]: [✔] Microsoft.Graph.Applications module version: 1.5.0
2022-10-17 22:08:47 [SUCCESS]: [✔] Az.KeyVault module version: 4.7.0
2022-10-17 22:08:47 [SUCCESS]: [✔] Az.OperationalInsights module version: 3.2.0
2022-10-17 22:08:47 [SUCCESS]: [✔] Az.Storage module version: 4.9.0
2022-10-17 22:08:47 [SUCCESS]: [✔] Az.Resources module version: 6.2.0
2022-10-17 22:08:47 [SUCCESS]: [✔] Az.MonitoringSolutions module version: 0.1.0
2022-10-17 22:08:48 [SUCCESS]: [✔] Az.RecoveryServices module version: 5.6.0
2022-10-17 22:08:48 [SUCCESS]: [✔] Az.Network module version: 4.20.1
2022-10-17 22:08:48 [SUCCESS]: [✔] Az.Monitor module version: 3.1.0
2022-10-17 22:08:48 [SUCCESS]: [✔] Az.Automation module version: 1.7.4
2022-10-17 22:08:48 [SUCCESS]: [✔] Powershell-Yaml module version: 0.4.2
2022-10-17 22:08:48 [SUCCESS]: [✔] Az.DataProtection module version: 0.4.0
2022-10-17 22:08:48 [SUCCESS]: [✔] Microsoft.Graph.Authentication module version: 1.9.6
2022-10-17 22:08:48 [SUCCESS]: [✔] Az.Accounts module version: 2.10.1
2022-10-17 22:08:48 [SUCCESS]: [✔] Az.Compute module version: 4.31.0
2022-10-17 22:08:48 [SUCCESS]: [✔] Az.Dns module version: 1.1.2
```
After running it (nothing is missing, obviously), I can still see the problem:
```
2022-10-17 22:13:33 [   INFO]: Attempting to authenticate with Microsoft Graph.
Please sign in with an account with admin rights over the Azure Active Directory you plan to use.
Welcome To Microsoft Graph!
2022-10-17 22:13:33 [SUCCESS]: [✔] Authenticated with Microsoft Graph
2022-10-17 22:13:33 [   INFO]: Ensuring that 'project.tre4mc.com' is registered with AAD...
Get-MgDomain: C:\***\deployment\safe_haven_management_environment\setup\Setup_SHM_AAD_Domain.ps1:36:14
Line |
  36 |  $aadDomain = Get-MgDomain | Where-Object { $_.Id -eq $config.domain.f …
     |               ~~~~~~~~~~~~
     | The 'Get-MgDomain' command was found in the module 'Microsoft.Graph.Identity.DirectoryManagement', but the module could not be
     | loaded. For more information, run 'Import-Module Microsoft.Graph.Identity.DirectoryManagement'.

New-MgDomain_CreateExpanded1: C:\***\deployment\safe_haven_management_environment\setup\Setup_SHM_AAD_Domain.ps1:40:5
Line |
  40 |      $aadDomain = New-MgDomain -Id $config.domain.fqdn
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | One or more errors occurred. (Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.13.0.0,
     | Culture=neutral, PublicKeyToken=***'. The system cannot find the file specified.)
```
> We don't have any kind of .devcontainer at the moment. If you think this would be useful, would you consider adding one in a PR?

It's quite an essential thing (for example, Microsoft TRE has it) - it saves a lot of time. I'm not keen to write it at the moment as we are not yet decided what TRE we are going to use.

**Comment by jemrobinson** [comment] 2022-10-18 09:52
This looks like a missing module check in the `CheckRequirements` script.

@david-salac: Can you try `Install-Module -Scope CurrentUser Microsoft.Graph.Identity.DirectoryManagement -RequiredVersion 1.10.0` and see if you can run the script after that?

**Comment by david-salac** [comment] 2022-10-18 11:23
Thanks, but unfortunately, it does not change anything (same error, different version in the error log):
```
     | One or more errors occurred. (Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.10.0.0,
     | Culture=neutral, PublicKeyToken=***'. The system cannot find the file specified.)
```

**Comment by jemrobinson** [comment] 2022-10-18 11:26
OK, can you also run `Install-Module -Scope CurrentUser -Name Microsoft.Graph.Authentication -RequiredVersion 1.10.0` ? Sorry - there might be multiple missing modules here as I think when we ran the pre-release tests we had the full set of `Microsoft.Graph` modules installed.

**Comment by david-salac** [comment] 2022-10-18 11:50
This helped, thanks. Now it logs a different error.

```
2022-10-18 12:43:08 [   INFO]: Attempting to authenticate with Microsoft Graph. Please sign in with an account with admin rights over the Azure Active 
Directory you plan to use.
Welcome To Microsoft Graph!
2022-10-18 12:43:08 [SUCCESS]: [✔] Authenticated with Microsoft Graph
2022-10-18 12:43:08 [   INFO]: Ensuring that 'project.tre4mc.com' is registered with AAD...
2022-10-18 12:43:09 [SUCCESS]: [✔] 'project.tre4mc.com' added as custom domain on SHM AAD.
2022-10-18 12:43:09 [   INFO]: Ensuring that 'project.tre4mc.com' is verified with AAD...
Deploy-DnsRecord: C:\*\data-safe-haven\deployment\safe_haven_management_environment\setup\Setup_SHM_AAD_Domain.ps1:60:17
Line |
  60 |          $null = Deploy-DnsRecord -DnsRecords $validationCode -RecordN …
     |                  ~~~~~~~~~~~~~~~~
     | The term 'Deploy-DnsRecord' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling
     | of the name, or if a path was included, verify that the path is correct and try again.

2022-10-18 12:43:10 [SUCCESS]: [✔] Verification TXT record added to 'project.tre4mc.com' DNS zone.
Confirm-MgDomain_Verify1: C:\*\data-safe-haven\deployment\safe_haven_management_environment\setup\Setup_SHM_AAD_Domain.ps1:79:9
Line |
  79 |          Confirm-MgDomain -DomainId $config.domain.fqdn | Out-Null
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Domain verification failed with the following error: 'Error in DNS verification. code=MissingRecord'.

2022-10-18 12:43:11 [   INFO]: Checking domain verification status on SHM AAD (attempt 1 of 10)...
2022-10-18 12:43:11 [WARNING]: Verification check failed. Retrying in 60 seconds...
```

**Comment by jemrobinson** [comment] 2022-10-18 11:59
@david-salac I've created a new branch [`1321-fix-deployment-issues`](https://github.com/alan-turing-institute/data-safe-haven/tree/1321-fix-deployment-issues) to track these fixes. Can you check that out and try again? It should have the fix for the missing `Deploy-DnsRecord` module too.

**Comment by david-salac** [comment] 2022-10-19 09:54
This helped, thanks, now it failes on `Domain verification failed with the following error: 'Error in DNS verification. code=MissingRecord'` - but I guess that's a configuration issue on my side. Thank you.

**Comment by jemrobinson** [comment] 2022-10-19 10:38
Maybe I can help you with this one too. Where are `tre4mc.com` and `project.tre4mc.com` registered? Are either/both DNS zones in Azure? Were either/both created by running these scripts?

**Comment by david-salac** [comment] 2022-10-19 11:31
Oh, thank you. Well, the domain was registered inside Azure, so NS records are correct - but it was registered in a different tenancy (but using the same subscription - not sure if that matters).

Also, speaking about it, would that be possible not to have your own domain and rather to use something like: https://whatever.uksouth.cloudapp.azure.com/ ? Just that I find it quite a shame to register a domain when not needed.

**Comment by jemrobinson** [comment] 2022-10-19 12:05
> Oh, thank you. Well, the domain was registered inside Azure, so NS records are correct - but it was registered in a different tenancy (but using the same subscription - not sure if that matters).

- The `Setup_SHM_DNS_Zone.ps1` script creates a new Azure DNS zone (probably `project.tre4mc.com` in your case). It then attempts to add an NS record for this zone to the parent (probably `tre4mc.com` in your case), printing an informational message that you should do this yourself if it cannot find the parent zone on Azure.
  - does your `tre4mc.com` zone have an NS record for `project`?
- The `Setup_SHM_AAD_Domain.ps1` script attempts to register your domain as an allowed user domain. In order to do this,  it needs the previous step to have successfully completed, such that adding a DNS record to `project.tre4mc.com` can be seen by AzureAD.
  - I think this is the step that failed, possibly because you haven't added the required NS records. Did a verification record get added to `project.tre4mc.com`? Can you read it using `nslookup` or similar?

> Also, speaking about it, would that be possible not to have your own domain and rather to use something like: https://whatever.uksouth.cloudapp.azure.com/ ? Just that I find it quite a shame to register a domain when not needed.

Not with the current setup. This domain is used for two things:
- the place that users go to in order to log in
- the domain that users belong to (username@custom_domain)

I don't think it would be possible to verify a `whatever.uksouth.cloudapp.azure.com` domain in AzureAD as a source of users.

**Comment by david-salac** [comment] 2022-10-19 13:15
Regarding that domain - yes, that makes sense. It's actually not a big deal to register a new one - I was just wondering how necessary it is - but you've explained it quite clearly.

Also, I added that NS record for that subdomain & waited a bit, but it's still logging the same error.
```
PS *> nslookup project.tre4mc.com
Server:  UnKnown
Address:  10.2.0.1

Name:    project.tre4mc.com
Served by:
- ns4-35.azure-dns.info

          project.tre4mc.com
- ns1-35.azure-dns.com

          project.tre4mc.com
- ns2-35.azure-dns.net

          project.tre4mc.com
- ns3-35.azure-dns.org

          project.tre4mc.com
```
But the error is the same:
```
2022-10-19 14:10:28 [   INFO]: Ensuring that 'project.tre4mc.com' is registered with AAD...
2022-10-19 14:10:28 [SUCCESS]: [✔] 'project.tre4mc.com' already present as custom domain on SHM AAD.
2022-10-19 14:10:28 [   INFO]: Ensuring that 'project.tre4mc.com' is verified with AAD...
2022-10-19 14:10:29 [SUCCESS]: [✔] Verification TXT record already exists in 'project.tre4mc.com' DNS zone.
Confirm-MgDomain_Verify1: *\data-safe-haven\deployment\safe_haven_management_environment\setup\Setup_SHM_AAD_Domain.ps1:80:9
Line |
  80 |          Confirm-MgDomain -DomainId $config.domain.fqdn | Out-Null
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Domain verification failed with the following error: 'Error in DNS verification. code=MissingRecord'.

2022-10-19 14:10:47 [   INFO]: Checking domain verification status on SHM AAD (attempt 1 of 10)...
2022-10-19 14:10:47 [WARNING]: Verification check failed. Retrying in 60 seconds...
```

**Comment by jemrobinson** [comment] 2022-10-19 13:30
It looks to me like you still haven't added a `project` NS record under `tre4mc.com`.

```
> nslookup -q=NS tre4mc.com
Server:		10.10.0.4
Address:	10.10.0.4#53

Non-authoritative answer:
tre4mc.com	nameserver = ns1-35.azure-dns.com.
tre4mc.com	nameserver = ns2-35.azure-dns.net.
tre4mc.com	nameserver = ns3-35.azure-dns.org.
tre4mc.com	nameserver = ns4-35.azure-dns.info.

Authoritative answers can be found from:
ns1-35.azure-dns.com	internet address = 150.171.10.35
ns1-35.azure-dns.com	has AAAA address 2603:1061:0:10::23
ns2-35.azure-dns.net	internet address = 150.171.16.35
ns2-35.azure-dns.net	has AAAA address 2620:1ec:8ec:10::23
ns3-35.azure-dns.org	internet address = 13.107.222.35
ns3-35.azure-dns.org	has AAAA address 2a01:111:4000:10::23
ns4-35.azure-dns.info	internet address = 13.107.206.35
ns4-35.azure-dns.info	has AAAA address 2620:1ec:bda:10::23
```

so `tre4mc.com` has nameservers that I can query.

```
> nslookup -q=NS project.tre4mc.com
Server:		10.10.0.4
Address:	10.10.0.4#53

Non-authoritative answer:
*** Can't find project.tre4mc.com: No answer

Authoritative answers can be found from:
```

but `project.tre4mc.com` does not have any queryable nameservers.

**Comment by david-salac** [comment] 2022-10-19 14:29
Thanks.

I see. So, it's probably not propagated everywhere yet... (it works correctly for me when I run it from home, but when I use VPN, it does not):
```
> nslookup -q=NS project.tre4mc.com
Server:  UnKnown
Address:  10.2.0.1

project.tre4mc.com      nameserver = ns2-35.azure-dns.net
project.tre4mc.com      nameserver = ns3-35.azure-dns.org
project.tre4mc.com      nameserver = ns4-35.azure-dns.info
project.tre4mc.com      nameserver = ns1-35.azure-dns.com
```

**Comment by jemrobinson** [comment] 2022-10-19 17:35
It's weird that it would take more than a few minutes if `tre4mc.com` is already an Azure DNS zone. Just to confirm:

1. do you have an NS record on your `tre4mc.com` DNS zone like the following?

<img width="849" alt="Screenshot 2022-10-19 at 18 35 21" src="https://user-images.githubusercontent.com/3502751/196764227-f3a2785e-26c4-400d-89c6-dcdc8602582f.png">

2. do you have a DNS zone for `project.tre4mc.com` which has matching nameservers for the `@` record?
  
<img width="881" alt="Screenshot 2022-10-19 at 18 32 33" src="https://user-images.githubusercontent.com/3502751/196763683-d07f941a-55d4-4eee-8f1f-e8933e24793f.png">

**Comment by david-salac** [comment] 2022-10-19 18:15
That really is strange, isn't it? It still does not work - yes, I have it exactly like that.
![ATI TRE Problem](https://github.com/civicdatacoop/miscellaneous/blob/main/error_ati_tre.gif?raw=true)

**Comment by jemrobinson** [comment] 2022-10-19 18:16
Can you also post a screenshot of the `@` record for the `project.tre4mc.com` zone? Just to confirm that it's using the same nameservers.

**Comment by david-salac** [comment] 2022-10-19 18:20
I don't understand now. I added that DNS record by using '+ Record set' button on top. There is no place for `@` in that (?)

**Comment by jemrobinson** [comment] 2022-10-19 18:25
Aha, I think you might have misunderstood the `You need to add the following NS records` step from [here](https://alan-turing-institute.github.io/data-safe-haven/develop/deployment/deploy_shm.html#register-custom-domain-with-azure-active-directory).

As part of running the `Setup_SHM_DNS_Zone.ps1` script, a **new** Azure DNS zone is created with the name `project.tre4mc.com`. It will be in a resource group called `RG_SHM_PROJECT_DNS_RECORDS`.

You need to ensure that the nameservers from the `@` record of this DNS zone match the ones delegated by the `project` NS record on the parent DNS record.

**Comment by david-salac** [comment] 2022-10-19 19:12
I don't understand. 
I added those DNS as that screenshot above suggest - values for NS "@" and NS "project" are identical. Yet, it still does not work

**Comment by david-salac** [comment] 2022-10-19 19:22
Ah I see now what you mean.
Well in @ record for main domain is:
`ns1-34.azure-dns.com.` (etc.)
But in @ for project.tre4mc.com is:
`ns1-35.azure-dns.com.` (etc.)
So it's not exactly the same. But the thing is - I have no way how to change it - these values are given by default. Plus, I'm not really sure if this is what causes problems (?)

**Comment by jemrobinson** [comment] 2022-10-19 20:47
You're right that you can't change the nameservers for the `project.tre4mc.com` DNS zone.

You need to change the `project` NS record in the `tre4mc.com` DNS zone to match. Follow [this guide from Azure](https://learn.microsoft.com/en-us/azure/dns/dns-operations-recordsets-portal#add-a-new-record-to-a-record-set) to change the contents of an existing record.

**Comment by david-salac** [comment] 2022-10-20 08:33
Thank you.
But the thing is, these records cannot be modified either on the domain or subdomain level. It's actually written in that document as well. See the section _Modify NS records at the zone apex_:
> ... However, you can't remove or modify the pre-populated Azure DNS name servers.

You cannot add them as well; both is obvious from the following print screen:
![Problem with NS records](https://github.com/civicdatacoop/miscellaneous/blob/main/ati_problem_ns.png?raw=true)

**Comment by david-salac** [comment] 2022-10-20 08:44
Please, ignore the post above - it's working correctly now (I was in '@', not in the 'project' NS record).
Thank you for being so helpful.

**Comment by jemrobinson** [comment] 2022-10-20 08:45
@david-salac As you correctly point out, you **can't** change the `@` record of either DNS zone. However, you **can** change the NS record called `project` that belongs to the `tre4mc.com` DNS zone. This is the one you have to change.

Here's an example using a domain that I own (`develop.dsgroupdev.co.uk` in place of your domain `tre4mc.com`)

## Parent DNS zone
<img width="1172" alt="Screenshot 2022-10-20 at 09 40 30" src="https://user-images.githubusercontent.com/3502751/196900528-6241a76b-8ad0-431a-9d8a-8fcfbe2aa8e7.png">

Here you can see that the `develop.dsgroupdev.co.uk` DNS zone has an NS record called `project` with incorrectly set NS records.

- Click on the `project` NS record

## project NS record
<img width="746" alt="Screenshot 2022-10-20 at 09 40 44" src="https://user-images.githubusercontent.com/3502751/196900535-31dd871d-625b-48e9-8073-4c053536f583.png">

Here you can see that the values of the record are editable

- change them to the ones you need for the `project.tre4mc.com` DNS zone
- earlier you mentioned these were `ns1-34-*` so I've shown that below

<img width="758" alt="Screenshot 2022-10-20 at 09 41 15" src="https://user-images.githubusercontent.com/3502751/196900539-8905ffc0-4a99-4e10-9d37-d66e55f7d06d.png">

- Click `Save`

## Back to the parent DNS zone

<img width="1206" alt="Screenshot 2022-10-20 at 09 41 32" src="https://user-images.githubusercontent.com/3502751/196900544-ce00225f-3f24-464f-ace4-cccc323cde11.png">

If you now go back to the parent DNS zone, you can see that the values for this NS record have been updated

**Comment by david-salac** [comment] 2022-10-20 09:40
Thank you.
I guess regarding this Issue - all is sorted (I have a new problem - but I will create a new Issue). Cheers.

**Closed as completed** 2022-10-24 09:57 UTC
Labels: bug
