### ISSUE TITLE
Support multiple subscriptions

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1633] opened 2023-10-06 08:18 UTC
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Currently all resources are deployed into the subscription used by `dsh init`. Each `shm` and `sre` deployment should have a `--subscription` option (and associated config file entry).

## :steam_locomotive: How could this be done?

- Update `config.py`
- Update `deploy_shm.py` and `deploy_sre.py`

**Comment by JimMadge** [comment] 2024-05-30 10:54
Duplicate of #1904

**Closed as completed by JimMadge** 2024-05-30 10:54 UTC
Labels: closing: duplicate, enhancement
